version: '3.8'

services:
  # Database
  quantashield-db:
    image: postgres:15-alpine
    container_name: quantashield-db
    environment:
      POSTGRES_DB: quantashield
      POSTGRES_USER: quantashield
      POSTGRES_PASSWORD: ${DB_PASSWORD:-quantashield_secure_2025}
    volumes:
      - quantashield_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - quantashield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantashield -d quantashield"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and sessions
  quantashield-redis:
    image: redis:7-alpine
    container_name: quantashield-redis
    ports:
      - "6379:6379"
    volumes:
      - quantashield_redis_data:/data
    networks:
      - quantashield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  quantashield-backend:
    build:
      context: ./quantashield-backend
      dockerfile: Dockerfile
    container_name: quantashield-backend
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://quantashield:${DB_PASSWORD:-quantashield_secure_2025}@quantashield-db:5432/quantashield
      - REDIS_URL=redis://quantashield-redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-jwt-secret-change-in-production}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_MICROSOFT_CLIENT_ID=${OAUTH_MICROSOFT_CLIENT_ID}
      - OAUTH_MICROSOFT_CLIENT_SECRET=${OAUTH_MICROSOFT_CLIENT_SECRET}
      - OAUTH_FACEBOOK_CLIENT_ID=${OAUTH_FACEBOOK_CLIENT_ID}
      - OAUTH_FACEBOOK_CLIENT_SECRET=${OAUTH_FACEBOOK_CLIENT_SECRET}
      - OAUTH_LINKEDIN_CLIENT_ID=${OAUTH_LINKEDIN_CLIENT_ID}
      - OAUTH_LINKEDIN_CLIENT_SECRET=${OAUTH_LINKEDIN_CLIENT_SECRET}
      - OAUTH_TWITTER_CLIENT_ID=${OAUTH_TWITTER_CLIENT_ID}
      - OAUTH_TWITTER_CLIENT_SECRET=${OAUTH_TWITTER_CLIENT_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      quantashield-db:
        condition: service_healthy
      quantashield-redis:
        condition: service_healthy
    networks:
      - quantashield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  quantashield-frontend:
    build:
      context: ./quantashield-frontend
      dockerfile: Dockerfile
    container_name: quantashield-frontend
    ports:
      - "3000:8080"
    depends_on:
      quantashield-backend:
        condition: service_healthy
    networks:
      - quantashield-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  quantashield_db_data:
    driver: local
  quantashield_redis_data:
    driver: local

networks:
  quantashield-network:
    driver: bridge

